version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: faq_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=faqs
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d faqs"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
